// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3meI6KlaqMYfeoxV3oSTWKaHg-fyUBs',
    appId: '1:927361261541:web:8c4c4bd7a98c454a08590c',
    messagingSenderId: '927361261541',
    projectId: 'fb-db-8727c',
    authDomain: 'fb-db-8727c.firebaseapp.com',
    storageBucket: 'fb-db-8727c.appspot.com',
    measurementId: 'G-H826G1PZV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLcStTmC3Tqzlv_brnhP2ZYSiC0w-ykc',
    appId: '1:927361261541:android:0c791bd3093797eb08590c',
    messagingSenderId: '927361261541',
    projectId: 'fb-db-8727c',
    storageBucket: 'fb-db-8727c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvGWkSH8LlAI-Tn3C_b98a5I4jhXqPP5I',
    appId: '1:927361261541:ios:9bcb22c6fe6771b708590c',
    messagingSenderId: '927361261541',
    projectId: 'fb-db-8727c',
    storageBucket: 'fb-db-8727c.appspot.com',
    iosBundleId: 'com.example.fbDb',
  );
}
